services:
  - type: web
    name: excel-analytics-platform
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start-backend
    envVars:
      - key: NODE_ENV
        value: development
